---
title: "About me"
theme: sandstone

subtitle: "PhD. Hugo G. Castelán Sánchez"
---

Hugo is a candidate for a Doctor of Science in the area of Cellular and Molecular Biology from the Autonomous University of the State of Morelos UAEM.
He has a master's degree in genomic sciences from the Mexico City Autonomous University and a bachelor's degree in Biological Pharmaceutical Chemistry from the National Autonomous University of Mexico UNAM.


During his undergraduate studies, he became interested in the study of viruses, and began working with the H3N2 Influenza virus, searching for viral quasi-species through next generation sequencing.

I continue studying viruses during my master's degree where I focus on evolutionary analysis of the sequences of the envelope proteins of RNA viruses such as Dengue, Hepatitis C and Bovine viral diarrhea virus.


I currently interested in studying viral diversity in extreme environments such as thermophiles and hypersaline and determining the role of viruses in the population structure of these ecosystems. 


