---
title: "Publications"
theme: sandstone
---

#2023 

#2022

#2021 

#2020 

1. Villacís, J., Reyes, J., Castelán-Sánchez, H., Dávila-Ramos, S., Lazo, M., Wali, A., Bodero, L., Toapanta, Y., Naranjo, C., Montero, L., Campos, J., Galas, M. and Gestal, M. (2020). OXA-48 Carbapenemase in Klebsiella pneumoniae Sequence Type 307 in Ecuador. Microorganisms, 8(3), p.435

#2019 

1. Gómez-Silva, B., Vilo-Muñoz, C., Galetović, A., Dong, Q., Castelán-Sánchez, H., & Pérez-Llano, Y. et al. (2019). Metagenomics of Atacama Lithobiontic Extremophile Life Unveils Highlights on Fungal Communities, Biogeochemical Cycles and Carbohydrate-Active Enzymes. Microorganisms, 7(12), 619. doi:10.3390/microorganisms7120619*

2. Castelán-Sánchez, HG., Elorrieta, P., Romoacca, P., Liñan-Torres, A., Sierra, J., Vera I, Batista-Garcia RA., Tenorio-Salgado S., Lizama-Uc G., Pérez-Rueda E., Quispe-Ricalde M.A. and Dávila-Ramos S. (2019). Intermediate-Salinity Systems at High Altitudes in the Peruvian Andes Unveil a High Diversity and Abundance of Bacteria and Viruses. Genes, 10(11), 891. doi:10.3390/genes10110891

3. Dávila-Ramos, S., Castelán-Sánchez, H., Martínez-Ávila, L., Sánchez-Carbente, M., Peralta, R., Hernández-Mendoza, A., Dobson, A., Gonzalez, R., Pastor, N. and Batista-García, R. (2019). A Review on Viral Metagenomics in Extreme Environments. Frontiers in Microbiology, 10. https://doi.org/10.3389/fmicb.2019.02403

4. Castelán-Sánchez, Hugo G., Itzel Lopéz-Rosas, Wendy A. García-Suastegui, Raúl Peralta, Alan D.W. Dobson, Ramón Alberto Batista-García, and Dávila-Ramos S. 2019. "Extremophile Deep-Sea Viral Communities From Hydrothermal Vents: Structural And Functional Analysis". Marine Genomics 46: 16-28. Elsevier BV. doi:10.1016/j.margen.2019.03.001.

5. Mamani, J. I., Pacheco, K. B., Elorrieta, P., Romoacca, P., Castelan, H., Davila, S., Sierra J & Quispe-Ricalde, M. A. (2019). Draft Genome Sequence of Halomonas elongata MH25661 Isolated from a Saline Creek in the Andes of Peru. Microbiol Resour Announc, 8(1), e00934-18.

#2018 

1. González-Durán, E., Vázquez-Pichardo, M., Torres-Flores, J., Garcés-Ayala, F., Méndez-Tenorio, A., Curiel-Quesada, E., Ortiz-Alcántara, J., Castelán-Sánchez, H., Salas-Benito, J., Torres-Longoria, B., López-Martínez, I., Hernández-Rivas, L., Membrillo-Hernández, J., Díaz-Quiñonez, J. and Ramírez-González, J. (2018). Genotypic variability analysis of DENV-1 in Mexico reveals the presence of a novel Mexican lineage. Archives of Virology, 163(6), pp.1643-1647.

2. Negrete-Abascal, E., Montes-Garcia, F., Vaca-Pacheco, S., Leyto-Gil, A., Fragoso-Garcia, E., Carvente-Garcia, R., Perez-Agueros, S., Castelan-Sanchez, H., Garcia-Molina, A., Villamar, T., Sánchez-Alonso, P. and Vazquez-Cruz, C. (2018). Genome Sequence of Actinobacillus seminis Strain ATCC 15768, a Reference Strain of Ovine Pathogens That Causes Infections in Reproductive Organs. Genome Announcements, 6(2).


#2017

1. Casteñeda-Ruelas, G., Carreón-Gaxiola, C., Castelán-Sánchez, H., Acatzi-Silva, A., Romero-Martínez, S., García-Molina, A. and Jiménez-Edeza, M. (2017). Draft Genome Sequences of 18 Salmonella enterica subsp. enterica Serovar Oranienburg Strains Isolated from Rivers in Northwestern Mexico. Genome Announcements, 5(10).


